### ISSUE TITLE
The block homepage delete permanentely the home page

### ISSUE THREAD

**Issue by angerangel** [gtbu/Typesetter5.2#1]
Hello,
if use push the lock button here:
[![Typesetter-Bug.jpg](https://i.postimg.cc/QMbJ1qh8/Typesetter-Bug.jpg)](https://postimg.cc/p9mjtzm4)
The home is removed from typesetter and you can't set any page anymore.
The workaround and to go directly to this page: **/gpEasy/index.php/Admin/Menu/Ajax?cmd=HomepageSelect**
So or you add this link or improve the lock button usage.

**Comment by gtbu** [comment]
Yes - You should never delete the root.  Put it to private. (please post such quetsions in the forum)
