### ISSUE TITLE
Creating new menu create unusable menus

### ISSUE THREAD

**Issue by angerangel** [gtbu/Typesetter5.2#2]
I tried to create a new menu, but I get a meanu where I can't insert or create pages:
[![Typesetter-Bug2.jpg](https://i.postimg.cc/NfsDGScN/Typesetter-Bug2.jpg)](https://postimg.cc/LhWLNyhf)

**Comment by gtbu** [comment]
Menus are created at the bottom of the pagemanager page - You must add leaves to make them usable
